import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import API from "../services";
import {
  FormControl,
  FormLabel,
  FormErrorMessage,
  FormHelperText,
  Input,
  useToast,
  useClipboard,
  Button,
} from "@chakra-ui/react";
import { useState } from "react";
const Home: NextPage = () => {
  const [originUrl, setOriginUrl] = useState("");
  const [result, setResult] = useState("");
  const [loading, setLoading] = useState(false);
  const toast = useToast();
  const { hasCopied, onCopy } = useClipboard(result);

  const convertLink = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      const res = await API.getShortLink({ originUrl });
      console.log(res);

      setResult(res.shortLink);
      toast({
        title: "Convert Success",
        status: "success",
        duration: 9000,
        isClosable: true,
      });
    } catch (error) {
      toast({
        title: "Convert Failed",
        status: "error",
        duration: 9000,
        isClosable: true,
      });
    }
    setLoading(false);
  };

  return (
    <div>
      <Head>
        <title>Convert Link</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-5 p-2 max-w-sm flex justify-center items-center flex-col m-auto gap-3">
        <form onSubmit={convertLink}>
          <FormControl>
            <FormLabel>Convert Link</FormLabel>
            <div className="flex gap-2 ">
              <Input
                type="text"
                onChange={(e) => setOriginUrl(e.target.value)}
              />
              <Button isLoading={loading} className="w-[150px]" type="submit">
                SUBMIT
              </Button>
            </div>
            {/* <FormHelperText>We'll never share your email.</FormHelperText> */}
          </FormControl>
        </form>
        <FormControl>
          <FormLabel>Result</FormLabel>
          <div className="flex gap-2">
            <Input type="text" value={result} readOnly />
            <Button className="w-[150px]" onClick={onCopy}>
              {hasCopied ? "COPIED!!!" : "COPY"}
            </Button>
          </div>
          {/* <FormHelperText>We'll never share your email.</FormHelperText> */}
        </FormControl>
      </main>
    </div>
  );
};

export default Home;
